const colors = {
  BACKGROUND_COLOR: 'white',
  BTN_DARK_PRIMARY_COLOR: '#1565c0',
  BTN_PRIMARY_COLOR: '#3483fa',
  BTN_LIGHT_PRIMARY_COLOR: 'rgba(65,137,230,.15)',
  BTN_TXT_PRIMARY_COLOR: 'white',
  BTN_TXT_LIGHT_PRIMARY_COLOR: '#3483fa',
  TXT_PRIMARY_COLOR: 'black',
  TXT_LIGHT_PRIMARY_COLOR: '#6b6b6b',
  TXT_SECONDARY_COLOR: 'white',
  ICON_BACKGROUND_SECONDARY_COLOR: '#f2f2f2',
  DIVIDER_COLOR: '#e0e0e0',
  HEADER_COLOR: '#3140C2',
};

export default colors;
